---
name: Deploy a Release
on: 
  push:
    tags:
      - '*' # Triggers for any tag

permissions:
  contents: write

jobs:
  pre-build-setup:
    name: Pre-Build Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Get Version
        id: get-tag
        run: |
          echo "thebuildtag=${{ github.ref_name }}" >> $GITHUB_ENV

    outputs:
      buildtag: ${{ env.thebuildtag }}

  build:
    name: Build and Deploy
    needs: [pre-build-setup]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.19.0
        with:
          maven-version: 3.9.11
          java-distribution: 'temurin'
          java-version: '25'

      - name: Create settings.xml
        run: |
          echo "<settings>" > settings.xml
          echo "  <servers>" >> settings.xml
          echo "    <server>" >> settings.xml
          echo "      <id>central</id>" >> settings.xml
          echo "      <username>${{ secrets.CENTRAL_USERNAME }}</username>" >> settings.xml
          echo "      <password>${{ secrets.CENTRAL_PASSWORD }}</password>" >> settings.xml
          echo "    </server>" >> settings.xml
          echo "  </servers>" >> settings.xml
          echo "  <profiles>" >> settings.xml
          echo "    <profile>" >> settings.xml
          echo "      <id>deploy-to-central</id>" >> settings.xml
          echo "      <properties>" >> settings.xml
          echo "        <gpg.passphrase>${{ secrets.GPG_PASSPHRASE }}</gpg.passphrase>" >> settings.xml
          echo "      </properties>" >> settings.xml
          echo "    </profile>" >> settings.xml
          echo "  </profiles>" >> settings.xml
          echo "</settings>" >> settings.xml
          
      # So that the jar versions are consistent with the docker tags, we set the version in the pom.xml
      # This should only run if the buildtag is not 'NA'
      - name: Update pom.xml version
        env:
          BUILDTAG: ${{ needs.pre-build-setup.outputs.buildtag }}
        run: mvn --batch-mode --no-transfer-progress versions:set -DnewVersion=$BUILDTAG
        
      - name: Build and test
        run: mvn --settings settings.xml --batch-mode --no-transfer-progress -p deploy-to-central clean deploy
        